drop schema if exists veleprodaja;
create schema veleprodaja collate utf8_unicode_ci;
use veleprodaja;


CREATE TABLE BANKA
(
	IdBanka               INTEGER NOT NULL,
	Naziv                 CHAR(64) NOT NULL,
	PostanskiBroj         INTEGER NOT NULL,
	 PRIMARY KEY (IdBanka)
)
;



CREATE TABLE JEDINICA_MJERE
(
	SifraJediniceMjere    CHAR(64) NOT NULL,
	OpisJediniceMjere     CHAR(64) NOT NULL,
	 PRIMARY KEY (SifraJediniceMjere)
)
;



CREATE TABLE KALKULACIJA
(
	RedniBroj             INTEGER NOT NULL,
	BrojFaktureDobavljaca  CHAR(64) NOT NULL,
	 PRIMARY KEY (RedniBroj)
)
;



CREATE TABLE KNJIGA_TRGOVINE_NA_VELIKO
(
	PoslovnaGodina        INTEGER NOT NULL,
	 PRIMARY KEY (PoslovnaGodina)
)
;



CREATE TABLE MJESTO
(
	PostanskiBroj         INTEGER NOT NULL,
	NazivMjesto           CHAR(64) NOT NULL,
	 PRIMARY KEY (PostanskiBroj)
)
;



CREATE TABLE NIVELACIJA
(
	RedniBroj             INTEGER NOT NULL,
	 PRIMARY KEY (RedniBroj)
)
;



CREATE TABLE OTPREMNICA
(
	RedniBroj             INTEGER NOT NULL,
	RedniBrojRacuna       INTEGER NULL,
	 PRIMARY KEY (RedniBroj)
)
;



CREATE TABLE PARTNER
(
	JIB                    CHAR(13) NOT NULL,
	Naziv                 VARCHAR(64) NOT NULL,
	Adresa                VARCHAR(64) NOT NULL,
	PostanskiBroj         INTEGER NOT NULL,
	 PRIMARY KEY (JIB)
)
;



CREATE TABLE RACUN
(
	RedniBrojRacuna       INTEGER NOT NULL auto_increment,
	Datum                 DATE NULL,
	 PRIMARY KEY (RedniBrojRacuna)
)
;



CREATE TABLE ROBA
(
	SifraRoba             INTEGER NOT NULL auto_increment,
	Naziv                 VARCHAR(64) NOT NULL,
	SifraJediniceMjere    VARCHAR(64) NOT NULL,
	 PRIMARY KEY (SifraRoba)
)
;



CREATE TABLE STAVKA_KALKULACIJE
(
	RedniBroj             INTEGER NOT NULL,
	SifraRoba             INTEGER NOT NULL,
	Kolicina              INTEGER NOT NULL,
	NabavnaCijena         FLOAT NOT NULL,
	Rabat                 FLOAT NOT NULL,
	VeleprodajnaCijena    FLOAT NOT NULL,
	 PRIMARY KEY (RedniBroj,SifraRoba)
)
;



CREATE TABLE STAVKA_KNJIGE_TRGOVINE_NA_VELIKO
(
	RedniBroj             INTEGER NOT NULL auto_increment,
	PoslovnaGodina        INTEGER NOT NULL,
	JIB                   CHAR(13) NOT NULL,
	Datum                 DATE NULL,
	 PRIMARY KEY (RedniBroj)
)
;



CREATE TABLE STAVKA_NIVELACIJE
(
	RedniBroj             INTEGER NOT NULL,
	SifraRoba             INTEGER NOT NULL,
	Kolicina              INTEGER NOT NULL,
	StaraCijena           FLOAT NOT NULL,
	NovaCijena            FLOAT NOT NULL,
	 PRIMARY KEY (RedniBroj,SifraRoba)
)
;



CREATE TABLE STAVKA_OTPREMNICE
(
	SifraRoba             INTEGER NOT NULL,
	RedniBroj             INTEGER NOT NULL,
	Kolicina              FLOAT NOT NULL,
	VeleprodajnaCijena    FLOAT NOT NULL,
	Rabat                 FLOAT NULL,
	 PRIMARY KEY (RedniBroj,SifraRoba)
)
;



CREATE TABLE TELEFON_BANKE
(
	BrojTelefona          INTEGER NOT NULL,
	IdBanka               INTEGER NOT NULL,
	 PRIMARY KEY (BrojTelefona,IdBanka)
)
;



CREATE TABLE TELEFON_PARTNERA
(
	BrojTelefona          VARCHAR(64) NOT NULL,
	JIB                   CHAR(13) NOT NULL,
	 PRIMARY KEY (BrojTelefona,JIB)
)
;



CREATE TABLE ZIRO_RACUN
(
	IdBanka               INTEGER NOT NULL,
	BrojZiroRacuna        CHAR(64) NOT NULL,
	JIB                    CHAR(13) NOT NULL,
	 PRIMARY KEY (BrojZiroRacuna,JIB,IdBanka)
)
;



ALTER TABLE BANKA
	ADD FOREIGN KEY BANKA_MJESTO (PostanskiBroj) REFERENCES MJESTO(PostanskiBroj)
;



ALTER TABLE KALKULACIJA
	ADD FOREIGN KEY (RedniBroj) REFERENCES STAVKA_KNJIGE_TRGOVINE_NA_VELIKO(RedniBroj)
		ON DELETE CASCADE
;



ALTER TABLE NIVELACIJA
	ADD FOREIGN KEY (RedniBroj) REFERENCES STAVKA_KNJIGE_TRGOVINE_NA_VELIKO(RedniBroj)
		ON DELETE CASCADE
;



ALTER TABLE OTPREMNICA
	ADD FOREIGN KEY (RedniBroj) REFERENCES STAVKA_KNJIGE_TRGOVINE_NA_VELIKO(RedniBroj)
		ON DELETE CASCADE
;


ALTER TABLE OTPREMNICA
	ADD FOREIGN KEY OTPREMNICA_RACUN (RedniBrojRacuna) REFERENCES RACUN(RedniBrojRacuna)
;



ALTER TABLE PARTNER
	ADD FOREIGN KEY PARTNER_SJEDISTE (PostanskiBroj) REFERENCES MJESTO(PostanskiBroj)
;



ALTER TABLE ROBA
	ADD FOREIGN KEY ROBA_JEDINICA_MJERE (SifraJediniceMjere) REFERENCES JEDINICA_MJERE(SifraJediniceMjere)
;



ALTER TABLE STAVKA_KALKULACIJE
	ADD FOREIGN KEY KALKULACIJA_STAVKE_KALKULACIJE (RedniBroj) REFERENCES KALKULACIJA(RedniBroj)
    ON DELETE CASCADE
;


ALTER TABLE STAVKA_KALKULACIJE
	ADD FOREIGN KEY STAVKA_KALKULACIJE_ROBA (SifraRoba) REFERENCES ROBA(SifraRoba)
;



ALTER TABLE STAVKA_KNJIGE_TRGOVINE_NA_VELIKO
	ADD FOREIGN KEY KNJIGA_STAVKA_KNJIGE (PoslovnaGodina) REFERENCES KNJIGA_TRGOVINE_NA_VELIKO(PoslovnaGodina)
;


ALTER TABLE STAVKA_KNJIGE_TRGOVINE_NA_VELIKO
	ADD FOREIGN KEY R_41 (JIB) REFERENCES PARTNER(JIB)
;



ALTER TABLE STAVKA_NIVELACIJE
	ADD FOREIGN KEY NIVELACIJA_STAVKE_NIVELACIJE (RedniBroj) REFERENCES NIVELACIJA(RedniBroj)
;


ALTER TABLE STAVKA_NIVELACIJE
	ADD FOREIGN KEY ROBA_STAVKA_NIVELACIJE (SifraRoba) REFERENCES ROBA(SifraRoba)
;



ALTER TABLE STAVKA_OTPREMNICE
	ADD FOREIGN KEY STAVKA_OTPREMNICE_ROBA (SifraRoba) REFERENCES ROBA(SifraRoba)
;


ALTER TABLE STAVKA_OTPREMNICE
	ADD FOREIGN KEY R_48 (RedniBroj) REFERENCES OTPREMNICA(RedniBroj)
;



ALTER TABLE TELEFON_BANKE
	ADD FOREIGN KEY BANKA_TELEFON_BANKE (IdBanka) REFERENCES BANKA(IdBanka)
;



ALTER TABLE TELEFON_PARTNERA
	ADD FOREIGN KEY R_39 (JIB) REFERENCES PARTNER(JIB)
;



ALTER TABLE ZIRO_RACUN
	ADD FOREIGN KEY ZIRO_RACUN_BANKA (IdBanka) REFERENCES BANKA(IdBanka)
;


ALTER TABLE ZIRO_RACUN
	ADD FOREIGN KEY PARTNER_ZIRO_RACUN (JIB) REFERENCES PARTNER(JIB)
;


